services:
  - type: web
    name: backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: babyaccountssql
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings

databases:
  - name: babyaccountssql
    databaseName: babyaccountssql
    user: babyaccountssql_user